name: Deploy to XDN (main)

on:
  push:
    branches:
      - main

jobs:
  deploy-to-xdn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm-proxy.fury.io/moovweb/
      - run: npm ci
      - run: npx xdn deploy --environment=default --team=moovweb-demos --site=rsf-ex-demo --token=$XDN_DEPLOY_TOKEN --branch=${{github.ref}} 
        env:
          XDN_DEPLOY_TOKEN: ${{secrets.XDN_DEPLOY_TOKEN}}
